# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Sat Apr 19 13:05:03 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import locale

locale.setlocale(locale.LC_ALL, '')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 510)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 25))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuFormula = QtGui.QMenu(self.menubar)
        self.menuFormula.setObjectName("menuFormula")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionDchains = QtGui.QAction(MainWindow)
        self.actionDchains.setObjectName("actionDchains")
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionNNF = QtGui.QAction(MainWindow)
        self.actionNNF.setObjectName("actionNNF")
        self.actionCNF = QtGui.QAction(MainWindow)
        self.actionCNF.setObjectName("actionCNF")
        self.actionSat = QtGui.QAction(MainWindow)
        self.actionSat.setObjectName("actionSat")
        self.actionLatex = QtGui.QAction(MainWindow)
        self.actionLatex.setObjectName("actionLatex")
        self.actionPedantic = QtGui.QAction(MainWindow)
        self.actionPedantic.setObjectName("actionPedantic")
        self.actionLength = QtGui.QAction(MainWindow)
        self.actionLength.setObjectName("actionLength")
        self.actionEvaluate = QtGui.QAction(MainWindow)
        self.actionEvaluate.setObjectName("actionEvaluate")
        self.actionResolution = QtGui.QAction(MainWindow)
        self.actionResolution.setObjectName("actionResolution")
        self.actionSufo = QtGui.QAction(MainWindow)
        self.actionSufo.setObjectName("actionSufo")
        self.actionClause_set = QtGui.QAction(MainWindow)
        self.actionClause_set.setObjectName("actionClause_set")
        self.actionImport_file = QtGui.QAction(MainWindow)
        self.actionImport_file.setObjectName("actionImport_file")
        self.actionClear_Session = QtGui.QAction(MainWindow)
        self.actionClear_Session.setObjectName("actionClear_Session")
        self.menuTools.addAction(self.actionLength)
        self.menuTools.addAction(self.actionSufo)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSat)
        self.menuTools.addAction(self.actionDchains)
        self.menuTools.addAction(self.actionEvaluate)
        self.menuTools.addAction(self.actionClause_set)
        self.menuTools.addAction(self.actionResolution)
        self.menuFormula.addAction(self.actionPedantic)
        self.menuFormula.addAction(self.actionNNF)
        self.menuFormula.addAction(self.actionCNF)
        self.menuFormula.addSeparator()
        self.menuFormula.addAction(self.actionLatex)
        self.menuFile.addAction(self.actionImport_file)
        self.menuFile.addAction(self.actionClear_Session)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFormula.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionNNF, QtCore.SIGNAL("activated()"), MainWindow.menu_nnf)
        QtCore.QObject.connect(self.actionDchains, QtCore.SIGNAL("activated()"), MainWindow.menu_dchains)
        QtCore.QObject.connect(self.actionCNF, QtCore.SIGNAL("activated()"), MainWindow.menu_cnf)
        QtCore.QObject.connect(self.actionSat, QtCore.SIGNAL("activated()"), MainWindow.menu_sat)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL("itemDoubleClicked(QListWidgetItem*)"), MainWindow.entry_clicked)
        QtCore.QObject.connect(self.actionLatex, QtCore.SIGNAL("activated()"), MainWindow.menu_latex)
        QtCore.QObject.connect(self.actionPedantic, QtCore.SIGNAL("activated()"), MainWindow.menu_pedantic)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), MainWindow.buttonPressed)
        QtCore.QObject.connect(self.lineEdit, QtCore.SIGNAL("returnPressed()"), MainWindow.buttonPressed)
        QtCore.QObject.connect(self.actionResolution, QtCore.SIGNAL("activated()"), MainWindow.menu_resolution)
        QtCore.QObject.connect(self.actionSufo, QtCore.SIGNAL("activated()"), MainWindow.menu_sufo)
        QtCore.QObject.connect(self.actionLength, QtCore.SIGNAL("activated()"), MainWindow.menu_length)
        QtCore.QObject.connect(self.actionClause_set, QtCore.SIGNAL("activated()"), MainWindow.menu_clause_set)
        QtCore.QObject.connect(self.actionEvaluate, QtCore.SIGNAL("activated()"), MainWindow.menu_evaluate)
        QtCore.QObject.connect(self.actionImport_file, QtCore.SIGNAL("activated()"), MainWindow.menu_import)
        QtCore.QObject.connect(self.actionClear_Session, QtCore.SIGNAL("activated()"), MainWindow.menu_clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Toolbox Classical Propositional Logic", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFormula.setTitle(QtGui.QApplication.translate("MainWindow", "Formula", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDchains.setText(QtGui.QApplication.translate("MainWindow", "dchains()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNNF.setText(QtGui.QApplication.translate("MainWindow", "nnf()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCNF.setText(QtGui.QApplication.translate("MainWindow", "cnf()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSat.setText(QtGui.QApplication.translate("MainWindow", "sat()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLatex.setText(QtGui.QApplication.translate("MainWindow", "latex()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPedantic.setText(QtGui.QApplication.translate("MainWindow", "pedantic()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLength.setText(QtGui.QApplication.translate("MainWindow", "length()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEvaluate.setText(QtGui.QApplication.translate("MainWindow", "evaluate()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResolution.setText(QtGui.QApplication.translate("MainWindow", "resolution()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSufo.setText(QtGui.QApplication.translate("MainWindow", "sufo()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClause_set.setText(QtGui.QApplication.translate("MainWindow", "clause_set()", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_file.setText(QtGui.QApplication.translate("MainWindow", "Import file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Session.setText(QtGui.QApplication.translate("MainWindow", "Clear Session", None, QtGui.QApplication.UnicodeUTF8))

